// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `parameter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.example;

/**
 * 输入输出参数
 **/
public interface _IParameterOperations
{
    /**
     * 单纯使用一个返回值的方式
     * @param __current The Current object for the invocation.
     **/
    boolean reg(String name, int age, Ice.Current __current);

    /**
     * 使用带输出参数的形式
     * @param __current The Current object for the invocation.
     **/
    void unReg(String name, Ice.IntHolder count, Ice.BooleanHolder successful, Ice.Current __current);
}
