// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `parameter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.example;

/**
 * 使用带输出参数的形式
 **/

public abstract class Callback_IParameter_unReg
    extends IceInternal.TwowayCallback implements _Callback_IParameter_unReg
{
    public final void __completed(Ice.AsyncResult __result)
    {
        IParameterPrxHelper.__unReg_completed(this, __result);
    }
}
