// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `parameter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.example;

/**
 * 输入输出参数
 **/
public interface IParameter extends Ice.Object,
                                    _IParameterOperations, _IParameterOperationsNC
{
    public static final String ice_staticId = "::example::IParameter";

    public static final long serialVersionUID = 1965198741L;
}
