// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `parameter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.example;

public final class IParameterHolder extends Ice.ObjectHolderBase<IParameter>
{
    public
    IParameterHolder()
    {
    }

    public
    IParameterHolder(IParameter value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof IParameter)
        {
            value = (IParameter)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _IParameterDisp.ice_staticId();
    }
}
