// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `ComplexInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.face.hello;

public abstract class Callback_IComplexInterface_visit
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<org.zigui.ice.face.hello.Person>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        IComplexInterfacePrxHelper.__visit_completed(this, __result);
    }
}
