// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `ComplexInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.face.hello;

public interface IComplexInterface extends Ice.Object,
                                           _IComplexInterfaceOperations, _IComplexInterfaceOperationsNC
{
    public static final String ice_staticId = "::hello::IComplexInterface";

    public static final long serialVersionUID = 1017561651L;
}
