// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `ComplexInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.face.hello;

/**
 * Provides type-specific helper functions.
 **/
public final class IComplexInterfacePrxHelper extends Ice.ObjectPrxHelperBase implements IComplexInterfacePrx
{
    private static final String __visit_name = "visit";

    public Person visit(Person person, Ice.BooleanOptional ageIncr)
    {
        return visit(person, ageIncr, null, false);
    }

    public Person visit(Person person, Ice.BooleanOptional ageIncr, java.util.Map<String, String> __ctx)
    {
        return visit(person, ageIncr, __ctx, true);
    }

    private Person visit(Person person, Ice.BooleanOptional ageIncr, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__visit_name);
        return end_visit(begin_visit(person, ageIncr, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_visit(Person person, Ice.BooleanOptional ageIncr)
    {
        return begin_visit(person, ageIncr, null, false, false, null);
    }

    public Ice.AsyncResult begin_visit(Person person, Ice.BooleanOptional ageIncr, java.util.Map<String, String> __ctx)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_visit(Person person, Ice.BooleanOptional ageIncr, Ice.Callback __cb)
    {
        return begin_visit(person, ageIncr, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_visit(Person person, Ice.BooleanOptional ageIncr, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_visit(Person person, Ice.BooleanOptional ageIncr, Callback_IComplexInterface_visit __cb)
    {
        return begin_visit(person, ageIncr, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_visit(Person person, Ice.BooleanOptional ageIncr, java.util.Map<String, String> __ctx, Callback_IComplexInterface_visit __cb)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_visit(Person person, 
                                       Ice.BooleanOptional ageIncr, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_visit(person, ageIncr, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_visit(Person person, 
                                       Ice.BooleanOptional ageIncr, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_visit(person, ageIncr, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_visit(Person person, 
                                       Ice.BooleanOptional ageIncr, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_visit(Person person, 
                                       Ice.BooleanOptional ageIncr, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_visit(Person person, 
                                        Ice.BooleanOptional ageIncr, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_visit(person, ageIncr, __ctx, __explicitCtx, __synchronous, 
                           new IceInternal.Functional_TwowayCallbackArg1<org.zigui.ice.face.hello.Person>(__responseCb, __exceptionCb, __sentCb)
                               {
                                   public final void __completed(Ice.AsyncResult __result)
                                   {
                                       IComplexInterfacePrxHelper.__visit_completed(this, __result);
                                   }
                               });
    }

    private Ice.AsyncResult begin_visit(Person person, 
                                        Ice.BooleanOptional ageIncr, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__visit_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__visit_name, __cb);
        try
        {
            __result.prepare(__visit_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            Person.__write(__os, person);
            __os.writeBool(1, ageIncr);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public Person visit(Person person, boolean ageIncr)
    {
        return visit(person, ageIncr, null, false);
    }

    public Person visit(Person person, boolean ageIncr, java.util.Map<String, String> __ctx)
    {
        return visit(person, ageIncr, __ctx, true);
    }

    private Person visit(Person person, boolean ageIncr, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__visit_name);
        return end_visit(begin_visit(person, ageIncr, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_visit(Person person, boolean ageIncr)
    {
        return begin_visit(person, ageIncr, null, false, false, null);
    }

    public Ice.AsyncResult begin_visit(Person person, boolean ageIncr, java.util.Map<String, String> __ctx)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_visit(Person person, boolean ageIncr, Ice.Callback __cb)
    {
        return begin_visit(person, ageIncr, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_visit(Person person, boolean ageIncr, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_visit(Person person, boolean ageIncr, Callback_IComplexInterface_visit __cb)
    {
        return begin_visit(person, ageIncr, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_visit(Person person, boolean ageIncr, java.util.Map<String, String> __ctx, Callback_IComplexInterface_visit __cb)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_visit(Person person, 
                                       boolean ageIncr, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_visit(person, ageIncr, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_visit(Person person, 
                                       boolean ageIncr, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_visit(person, ageIncr, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_visit(Person person, 
                                       boolean ageIncr, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_visit(Person person, 
                                       boolean ageIncr, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_visit(person, ageIncr, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_visit(Person person, 
                                        boolean ageIncr, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_visit(person, ageIncr, __ctx, __explicitCtx, __synchronous, 
                           new IceInternal.Functional_TwowayCallbackArg1<org.zigui.ice.face.hello.Person>(__responseCb, __exceptionCb, __sentCb)
                               {
                                   public final void __completed(Ice.AsyncResult __result)
                                   {
                                       IComplexInterfacePrxHelper.__visit_completed(this, __result);
                                   }
                               });
    }

    private Ice.AsyncResult begin_visit(Person person, 
                                        boolean ageIncr, 
                                        java.util.Map<String, String> __ctx, 
                                        boolean __explicitCtx, 
                                        boolean __synchronous, 
                                        IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__visit_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__visit_name, __cb);
        try
        {
            __result.prepare(__visit_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            Person.__write(__os, person);
            __os.writeBool(1, ageIncr);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public Person end_visit(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __visit_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            Person __ret = null;
            __ret = Person.__read(__is, __ret);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __visit_completed(Ice.TwowayCallbackArg1<Person> __cb, Ice.AsyncResult __result)
    {
        org.zigui.ice.face.hello.IComplexInterfacePrx __proxy = (org.zigui.ice.face.hello.IComplexInterfacePrx)__result.getProxy();
        Person __ret = null;
        try
        {
            __ret = __proxy.end_visit(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IComplexInterfacePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), IComplexInterfacePrx.class, IComplexInterfacePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IComplexInterfacePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), IComplexInterfacePrx.class, IComplexInterfacePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IComplexInterfacePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), IComplexInterfacePrx.class, IComplexInterfacePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IComplexInterfacePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), IComplexInterfacePrx.class, IComplexInterfacePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static IComplexInterfacePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, IComplexInterfacePrx.class, IComplexInterfacePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static IComplexInterfacePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, IComplexInterfacePrx.class, IComplexInterfacePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::hello::IComplexInterface"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, IComplexInterfacePrx v)
    {
        __os.writeProxy(v);
    }

    public static IComplexInterfacePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            IComplexInterfacePrxHelper result = new IComplexInterfacePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
