// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `ComplexInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.face.hello;

public interface IComplexInterfacePrx extends Ice.ObjectPrx
{
    public Person visit(Person person);

    public Person visit(Person person, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_visit(Person person);

    public Ice.AsyncResult begin_visit(Person person, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_visit(Person person, Ice.Callback __cb);

    public Ice.AsyncResult begin_visit(Person person, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_visit(Person person, Callback_IComplexInterface_visit __cb);

    public Ice.AsyncResult begin_visit(Person person, java.util.Map<String, String> __ctx, Callback_IComplexInterface_visit __cb);

    public Ice.AsyncResult begin_visit(Person person, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_visit(Person person, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_visit(Person person, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_visit(Person person, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<Person> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Person end_visit(Ice.AsyncResult __result);
}
