// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `ComplexInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.face.hello;

public final class IComplexInterfaceHolder extends Ice.ObjectHolderBase<IComplexInterface>
{
    public
    IComplexInterfaceHolder()
    {
    }

    public
    IComplexInterfaceHolder(IComplexInterface value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof IComplexInterface)
        {
            value = (IComplexInterface)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _IComplexInterfaceDisp.ice_staticId();
    }
}
