// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.zigui.ice.face.hello;

public interface IHello extends Ice.Object,
                                _IHelloOperations, _IHelloOperationsNC
{
    public static final String ice_staticId = "::hello::IHello";

    public static final long serialVersionUID = 419761140L;
}
